"""Independent CPU audit of the completed, rejected TRAIN fixed-grid candidate.

Reads public observations without importing candidate, runner, or report code.
Stored grid shape/bytes and selection are checkable here; fitting from original
captures is LOCAL_ONLY and is not independently regenerated by this command.
"""
import argparse
import json
import math
from pathlib import Path
import time
from .grid_inherited import digest, read
from .grid_verify import quotient, regression_check
from .resources import evidence_root


def verify(root=None):
    import numpy as np
    root = evidence_root(root)
    run = root / "data/benchmarks/grid_feedback/candidate"
    diagnostic = root / "data/benchmarks/grid_feedback/diagnostic"
    frozen = read(run / "freeze.json")
    protocol = frozen["protocol"]
    bound = frozen["binding"]
    source_checks = {}
    for rel, expected in bound["sources"].items():
        actual = digest(root / rel)
        if actual != expected:
            raise ValueError("FROZEN_CANDIDATE_SOURCE_CHANGED:" + rel)
        source_checks[rel] = actual
    if digest(diagnostic / "freeze.json") != bound["parent_freeze_sha256"]:
        raise ValueError("PARENT_FREEZE_CHANGED")
    summary_path = root / "results/grid_feedback/diagnostic_summary.json"
    if digest(summary_path) != bound["diagnostic_summary_sha256"]:
        raise ValueError("SELECTION_INPUT_CHANGED")
    prior = read(summary_path)
    expected = read(root / "results/grid_feedback/candidate_summary.json")
    selection = read(run / "selection_input_receipt.json")
    execution = read(run / "execution.json")
    paths = [p for p in run.rglob("*") if p.is_file()]
    before = {str(p.relative_to(root)): digest(p) for p in paths}
    grid_path = run / "fixed_grids.npz"
    if digest(grid_path) != selection["grid_sha256"] or digest(grid_path) != expected["grid_sha256"]:
        raise ValueError("GRID_HASH_CHANGED")
    arrays = []
    with np.load(grid_path, allow_pickle=False) as data:
        required = {f"{layer}/{kind}" for layer in (0, 12, 22) for kind in ("low_offsets", "low_scales")}
        if set(data.files) != required:
            raise ValueError("GRID_LAYER_COVERAGE")
        for name in sorted(data.files):
            value = data[name]
            if value.shape != (16, 120, 4, 1) or value.dtype != np.float16 or not np.isfinite(value).all():
                raise ValueError("GRID_STORAGE_SCHEMA")
            if name.endswith("low_scales") and not (value > 0).all():
                raise ValueError("NONPOSITIVE_GRID_SCALE")
            arrays.append({"name": name, "shape": list(value.shape), "dtype": str(value.dtype), "bytes": value.nbytes})
    grid_bytes = sum(a["bytes"] for a in arrays)
    if grid_bytes != selection["static_FP16_grid_bytes"]:
        raise ValueError("GRID_BYTE_LEDGER")
    planned = {(r["document"], r["layer"]) for r in selection["fit_inputs"]}
    seen, observations, documents = set(), [], {}
    for path in sorted((run / "cases").glob("*.json")):
        row = read(path)
        key = row["document"], row["layer"]
        if key not in planned or key in seen:
            raise ValueError("CANDIDATE_CASE_COVERAGE")
        seen.add(key)
        if row["status"] != "COMPLETE" or row["failure"] is not None or row["completed_tokens"] != 256:
            raise ValueError("CANDIDATE_FAILURE_REQUIRES_FULL_PANEL_UNDEFINED")
        if digest(path.with_suffix(".npz")) != row["sha256"]:
            raise ValueError("CANDIDATE_OBSERVATION_HASH")
        with np.load(path.with_suffix(".npz"), allow_pickle=False) as data:
            values = data["values"].copy()
        if row["fields"] != ["readout_sse", "late_readout_sse", "clipped_values", "low_values"] or values.shape != (256, 4) or not np.isfinite(values).all():
            raise ValueError("CANDIDATE_SCHEMA")
        for index, (loss, late, clipped, count) in enumerate(values.tolist()):
            if loss < 0 or late != (loss if index >= 128 else 0) or count != 16 * 120 * 128:
                raise ValueError("CANDIDATE_WINDOW_OR_DENOMINATOR")
            if clipped != int(clipped) or not 0 <= clipped <= count:
                raise ValueError("CANDIDATE_CLIPPING_COUNT")
        scored = values[protocol["scored_start"]:].tolist()
        observations.extend(scored)
        documents.setdefault(key[0], []).extend(row[0] for row in scored)
    if seen != planned or len(seen) != 18 or execution["status"] != "COMPLETE" or execution["failure_count"] != 0:
        raise ValueError("CANDIDATE_INCOMPLETE")
    totals = [math.fsum(row[index] for row in observations) for index in range(4)]
    ratio = totals[0] / prior["totals"]["LEGACY_P_PRE"]["readout_sse"]
    late_ratio = totals[1] / prior["totals"]["LEGACY_P_PRE"]["late_readout_sse"]
    clipped_fraction = totals[2] / totals[3]
    document_ratios = {doc: math.fsum(values) / prior["documents"][doc]["LEGACY_P_PRE"] for doc, values in documents.items()}
    comparisons = [regression_check(ratio, expected["readout_vs_legacy"]["value"]),
                   regression_check(late_ratio, expected["late_vs_legacy"]["value"]),
                   regression_check(clipped_fraction, expected["clipped_fraction"]["value"])]
    comparisons.extend(regression_check(value, expected[field]) for value, field in zip(totals,
        ("recurrent_readout_sse", "late_sse", "clipped_values", "low_values")))
    comparisons.extend(regression_check(value, expected["document_ratios"][doc]["value"]) for doc, value in document_ratios.items())
    rule = protocol["selection"]
    gate = {"complete_panel": True, "pooled_recurrent": ratio <= rule["pooled_recurrent_ratio_max"],
            "late": late_ratio <= rule["late_ratio_max"],
            "each_document": all(value <= rule["each_document_ratio_max"] for value in document_ratios.values()),
            "clipping": clipped_fraction <= rule["clipped_fraction_max"], "no_failures": True,
            "source_input_unchanged": execution["source_input_unchanged"]}
    if gate != expected["cpu_gate"]["checks"] or all(gate.values()) != expected["cpu_gate"]["passed"]:
        raise ValueError("CANDIDATE_GATE_MISMATCH")
    controls = read(run / "component_controls.json")
    if controls["triggered"] != prior["component_repeat_triggered"] or not controls["triggered"]:
        raise ValueError("COMPONENT_TRIGGER")
    component_expected = {(doc, layer, token, arm) for doc, layer in planned
                          for token in protocol["snapshot_tokens"] for arm in ("R2_HOLD_OFFSET", "R2_HOLD_SCALE")}
    component_seen, component_rows = set(), {}
    for row in controls["rows"]:
        key = row["document"], row["layer"], row["token"], row["arm"]
        if key not in component_expected or key in component_seen or row["writes"] != 16:
            raise ValueError("COMPONENT_COVERAGE")
        component_seen.add(key)
        held = "low_offsets" if row["arm"] == "R2_HOLD_OFFSET" else "low_scales"
        if row["payload_changed_elements"][held] != 0 or row["payload_changed_elements"]["high_values"] != 0:
            raise ValueError("HELD_COMPONENT_CHANGED")
        component_rows.setdefault(row["arm"], []).append(row)
        baseline_receipt = read(diagnostic / "cases" / f"{key[0]}_L{key[1]}__R2_OFFSET.json")
        baseline_snap = next(r for r in baseline_receipt["snapshots"] if r["token"] == key[2])
        comparisons.append(regression_check(row["first_sse"], baseline_snap["first_sse"]))
    if component_seen != component_expected:
        raise ValueError("MISSING_COMPONENT_CONTROL")
    component_totals = {}
    for arm, rows in component_rows.items():
        component_totals[arm] = {field: math.fsum(r[field] for r in rows) for field in
            ("first_sse", "physical_drift_sse", "affine_drift_sse", "repeat_clipped_values")}
        for field, value in component_totals[arm].items():
            comparisons.append(regression_check(value, expected["component_controls"][arm]["clipped_values" if field == "repeat_clipped_values" else field]))
    total_tokens = 18 * 256
    component_snapshots = len(component_expected)
    component_calls = {"recurrent_update_attempts": 0, "codec_write_attempts": component_snapshots * 16,
                       "affine_control_attempts": component_snapshots * 16, "future_transition_attempts": 0,
                       "fp64_small_group_batch_attempts": component_snapshots * 31}
    if execution["component_operations"] != component_calls or controls["operation_counts"] != component_calls:
        raise ValueError("COMPONENT_CALL_LEDGER")
    for field, count in (("fit_updates", total_tokens * 2), ("fit_codec_writes", total_tokens),
                         ("evaluation_updates", total_tokens * 2), ("evaluation_codec_writes", total_tokens)):
        if execution[field] != count:
            raise ValueError("CANDIDATE_CALL_LEDGER")
    after = {str(p.relative_to(root)): digest(p) for p in paths}
    if before != after or any(digest(root / rel) != value for rel, value in source_checks.items()):
        raise ValueError("CANDIDATE_INPUT_OR_SOURCE_MUTATED")
    return {"run_id": protocol["run_id"], "verification_status": "PASS_INCLUDED_OBSERVATIONS",
            "scientific_selection": "REJECTED_CPU_QUALITY_GATE", "candidate_gate": gate,
            "recurrent_readout_ratio_vs_legacy": ratio, "late_ratio_vs_legacy": late_ratio,
            "clipped_values": int(totals[2]), "low_values": int(totals[3]), "clipped_fraction": clipped_fraction,
            "document_ratios": document_ratios, "component_controls": component_totals,
            "completed_cases": 18, "component_snapshot_rows": component_snapshots,
            "comparison_count": len(comparisons), "maximum_comparison_abs_error": max(comparisons),
            "source_binding": "PASS_EXACT_FROZEN_SOURCE", "input_immutability": "PASS",
            "storage_ledger": {"arrays": arrays, "fitted_grid_total_bytes_48heads": grid_bytes,
                               "metadata_bytes_per_head": 120 * 4 * 2 * 2,
                               "payload_bytes_per_head": 120 * (128 + 4 * 2 * 2) + 8 * 128 * 2,
                               "FixedGrid_instance_grid_copy_bytes_16heads": 16 * 120 * 4 * 2 * 2,
                               "copy_note": "FixedGrid clones one layer grid at construction; payload metadata aliases that copy and must not be counted again. Original fitted grid remains separate. Source-derived allocation, not measured VRAM.",
                               "H32_bytes_per_Arm_instance": 32 * 32 * 4,
                               "residual_bytes": 0, "RNG_bytes": 0,
                               "packed_runtime_and_peak_memory": "NOT_MEASURED_CPU_EQUATION_HARNESS_ONLY"},
            "fit_reproduction_level": "Stored FP16 grids and source contract checked; original captures LOCAL_ONLY, min/max fitting not independently regenerated here",
            "failure_resume_limits": "All observed fit/replay cases completed. Exceptional interruption, failed-write tensor retention, and resume were not exercised; inferred completed-token counters are valid only for this failure-free run.",
            "new_model_forwards": 0, "GPU_seconds": 0}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)
    if args.out.exists():
        raise FileExistsError("No verification receipt overwrite")
    started, cpu = time.monotonic(), time.process_time()
    result = verify(args.root)
    result["execution"] = {"CPU_wall_seconds": time.monotonic() - started,
                           "CPU_process_seconds": time.process_time() - cpu, "threads": 1}
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(result, indent=2, allow_nan=False) + "\n")
    print(json.dumps({k: result[k] for k in ("verification_status", "scientific_selection", "maximum_comparison_abs_error", "execution")}))


if __name__ == "__main__":
    main()
